name: Print Software Versions
on:
  push:
    branches: main
jobs:
  PrintApplicationServerVersions:
    name: Application Server (BL) Versions (Java Stack)
    runs-on: ubuntu-latest
    steps:
      - name: Print Java Version
        run: java --version
      - name: Print Node Version
        run: node --version
      - name: Print Maven/Gradle Version
        run: mvn --version
  PrintDBMSVersions:
    name: Database Server (AL) Versions (SQL DB)
    runs-on: ubuntu-latest
    needs: [PrintApplicationServerVersions]
    steps:
      - name: Print PostgreSQL Version
        run: psql --version
      - name: Print MySQL Version
        run: mysql --version
